---
title: "Endometrium driver mutation burden model"
author: "Luiza Moore"
date: "13 December 2018"
output: html_document
---

```{r Libraries, message=FALSE, warning=FALSE}
library(readr)
library(tidyr)
library(dplyr)
library(ggplot2)
library(readxl)
library(magrittr)
library(lme4)
library(lmerTest)
require(MASS)
require(car)
library(sjPlot)
library(pbkrtest)
```

## Load in data
```{r endom_burden, message=FALSE, warning=FALSE}
  endom_burden<- read_excel("~/Desktop/Endometrium_vaf_burden_drivers29112018.xls")
  endom_burden.summary <- 
  endom_burden %>% dplyr::select(Age, BMI, PatientID, SampleID, Seq_X, Sample_Median_Vaf, Subs, Indels, Driver_status, Total_drivers, Parity) %>%  distinct()
  head(endom_burden)
# Only include donors with data on BMI and parity (15/18 donors)
  d <- as.data.frame(endom_burden.summary)
  d[is.na(d)] <- 0
  d1<-d[!is.na(as.numeric(d$Parity)), ]
  d2<-d1[!is.na(as.numeric(d1$BMI)), ]
  dim(d2)
  endom_burden<-d2
# Casting of variables i.e character numeric etc
  endom_burden %>% tbl_df()
# Change BMI to numeric
  endom_burden$BMI <- as.numeric(endom_burden$BMI)
  endom_burden$Parity <- as.numeric(endom_burden$Parity)
  head(endom_burden)
```


### Fit generalised mixed-effect model with poisson distribution

```{r Fit generalised mixed-effect model with poisson distribution, message=FALSE, warning=FALSE}
### AGE ###
# What is the effect of age on accumulation of driver mutations?
# Reduced model 1
  reduced_glmer_model1 = glmer(Total_drivers ~ Age + (Age-1|PatientID), data=endom_burden, REML=F, 
  family = "poisson")
  summary(reduced_glmer_model1)

### PARITY ###
# What is the effect of parity on accumulation of driver mutations?
# Full glmer model 1
  full_glmer_model1 = glmer(Total_drivers ~ Age + Parity + (Age - 1|PatientID), data=endom_burden, REML=F, family = "poisson")
  summary(full_glmer_model1)  

# Compare the two glmer models (parametric bootstrapping)
  PBmodcomp(full_glmer_model1, reduced_glmer_model1, nsim = 1000, ref = NULL, seed=NULL, cl = NULL, details = 0)  

# BODY MASS INDEX (BMI)
# Does BMI have an effect on accumulation of driver mutations?
# Full glmer model2
  full_glmer_model2 = glmer(Total_drivers ~ Age + Parity +BMI +(Age - 1|PatientID), data=endom_burden, REML=F, family = "poisson")
  summary(full_glmer_model2)
# Compare the two glmer models (parametric bootstrapping)
  PBmodcomp(full_glmer_model2, full_glmer_model1, nsim = 1000, ref = NULL, seed=NULL, cl = NULL, details = 0)  
  
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
